/**
 * @license
 * Copyright 2017 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

export const LESCLASSES = {
  0: 'tanche, Tinca tinca',
  1: 'poisson rouge, Carassius auratus',
  2: 'grand requin blanc, requin blanc, mangeur d\'hommes, requin mangeur d\'hommes' +
      'Carcharodon carcharias',
  3: 'requin tigre, Galeocerdo cuvieri',
  4: 'requin-marteau, requin-marteau',
  5: 'rayons électriques, crampes, poissons engourdis, torpilles',
  6: 'Stingray',
  7: 'coq',
  8: 'poule',
  9: 'autruche, Struthio camelus',
  10: 'Brouillage, Fringilla montifringilla',
  11: 'chardonneret, Carduelis carduelis',
  12: 'pinson de la maison, linotte, Carpodacus mexicanus',
  13: 'junco, snowbird',
  14: 'Bruant indigo, pinson indigo, oiseau indigo, Passerina cyanea',
  15: 'robin, robin américain, Turdus migratorius',
  16: 'bulbul',
  17: 'geai',
  18: 'pie',
  19: 'mésanges',
  20: 'eau ouzel, louche',
  21: 'cerf-volant',
  22: 'pygargue à tête blanche, aigle américain, Haliaeetus leucocephalus',
  23: 'vautour',
  24: 'chouette lapone, Strix nebulosa',
  25: 'Salamandre européenne, Salamandra salamandra',
  26: 'triton commun, Triturus vulgaris',
  27: 'eft',
  28: 'salamandre maculée, Ambystoma maculatum',
  29: 'axolotl, chiot de boue, Ambystoma mexicanum',
  30: 'ouaouaron, Rana catesbeiana',
  31: 'rainette, rainette',
  32: 'grenouille à queue, crapaud, crapaud, crapaud, Ascaphus trui',
  33: 'tortue caouanne, Caretta caretta',
  34: 'tortue luth, tortue luth, tortue coriace, Dermochelys coriacea',
  35: 'tortue de boue',
  36: 'terrapin',
  37: 'tortue-boîte, boîte-tortue',
  38: 'gecko à bandes',
  39: 'iguane commun, iguane, iguane iguane',
  40: 'caméléon américain, anole, Anolis carolinensis',
  41: 'whiptail, whiptail lizard',
  42: 'agama',
  43: 'lézard à collerette, Chlamydosaurus kingi',
  44: 'Lézard alligator',
  45: 'Monstre de Gila, Heloderma suspectum',
  46: 'Lézard vert, Lacerta viridis',
  47: 'caméléon africain, Chamaeleo chamaeleon',
  48: 'Dragon de Komodo, lézard de Komodo, lézard dragon, lézard géant' +
      'Varanus komodoensis',
  49: 'Crocodile d\'Afrique, crocodile du Nil, Crocodylus niloticus',
  50: 'Alligator américain, Alligator mississipiensis',
  51: 'triceratops',
  52: 'serpent tonnerre, ver serpent, Carphophis amoenus',
  53: 'serpent à collier, serpent à collier, serpent à anneau',
  54: 'serpent de hognose, additionneur de bouffée, vipère de sable',
  55: 'serpent vert, serpent d\'herbe',
  56: 'serpent royal, serpent royal',
  57: 'couleuvre rayée, couleuvre à collier',
  58: 'serpent d\'eau',
  59: 'serpent de vigne',
  60: 'serpent de nuit, Hypsiglena torquata',
  61: 'boa constrictor, Constrictor constrictor',
  62: 'python noir, serpent noir, Python sebae',
  63: 'Cobra indien, Naja naja',
  64: 'mamba vert',
  65: 'serpent de mer',
  66: 'vipère à cornes, cerastes, vipère de sable, asperges à cornes, Cerastes cornutus',
  67: 'Crotalus adamanteus',
  68: 'Crotale cornu, Crotalus cerastes',
  69: 'trilobite',
  70: 'moissonneur, papa longlegs, Phalangium opilio',
  71: 'scorpion',
  72: 'araignée de jardin noire et dorée, Argiope aurantia',
  73: 'araignée de grange, Araneus cavaticus',
  74: 'araignée de jardin, Aranea diademata',
  75: 'veuve noire, Latrodectus mactans',
  76: 'tarentule',
  77: 'araignée de loup, araignée de chasse',
  78: 'coche',
  79: 'mille-pattes',
  80: 'tétras lyre',
  81: 'lagopède',
  82: 'gélinotte huppée, perdrix, Bonasa ombellus',
  83: 'poulet des prairies, tétras des prairies, pintades',
  84: 'paon',
  85: 'caille',
  86: 'perdrix',
  87: 'Gris africain, Gris africain, Psittacus erithacus',
  88: 'aras',
  89: 'cacatoès à crête de soufre, Kakatoe galerita, Cacatua galerita',
  90: 'Lorike',
  91: 'coucal',
  92: 'mangeur d\'abeilles',
  93: 'calao',
  94: 'Colibri',
  95: 'jacamar',
  96: 'toucan',
  97: 'drake',
  98: 'Mergus à poitrine rouge, Mergus serrator',
  99: 'oie',
  100: 'cygne noir, Cygnus atratus',
  101: 'tusker',
  102: 'échidné, fourmilier épineux, fourmilier',
  103: 'ornithorynque, bec de canard, ornithorynque à bec de canard, ornithorynque à bec de canard,' +
      'Ornithorhynchus anatinus',
  104: 'wallaby, brosse kangourou',
  105: 'koala, ours koala, ours kangourou, ours indigène, Phascolarctos cinereus',
  106: 'wombat',
  107: 'méduses',
  108: 'anémone de mer, anémone',
  109: 'corail cérébral',
  110: 'ver plat, platyhelminth',
  111: 'nématode, ver nématode, ver rond',
  112: 'conque',
  113: 'escargot',
  114: 'limace',
  115: 'limace de mer, nudibranche',
  116: 'chiton, coquille de manteau de courrier, berceau marin, polyplacophore',
  117: 'Nautile en chambre, Nautile nacré, Nautile',
  118: 'Crabe dormeur, Cancer magister',
  119: 'crabe commun, Cancer irroratus',
  120: 'crabe de violoneux',
  121: 'crabe royal, crabe d\'Alaska, crabe royal d\'Alaska, crabe royal d\'Alaska' +
      'Paralithodes camtschatica',
  122: 'Homard américain, homard du Nord, homard du Maine, Homarus americanus',
  123: 'langouste, langouste, langouste, langouste, écrevisse, mer' +
      'écrevisse',
  124: 'écrevisses, écrevisses, crawdad, crawdaddy',
  125: 'crabe ermite',
  126: 'isopode',
  127: 'cigogne blanche, Ciconia ciconia',
  128: 'cigogne noire, Ciconia nigra',
  129: 'spatule',
  130: 'flamingo',
  131: 'petit héron, Egretta caerulea',
  132: 'Aigrette d\'Amérique, grand héron, Egretta albus',
  133: 'butor',
  134: 'grue',
  135: 'limpkin, Aramus pictus',
  136: 'gallinule européen, Porphyrio porphyrio',
  137: 'foulque d\'Amérique, poule des marais, poule de boue, poule d\'eau, Fulica americana',
  138: 'outarde',
  139: 'Turnstone rouge, Arenaria interpres',
  140: 'Bécasseau à dos rouge, Dunlin, Erolia alpina',
  141: 'Redshank, Tringa totanus',
  142: 'dowitcher',
  143: 'huîtrier, attrape-huîtres',
  144: 'pélican',
  145: 'manchot royal, Aptenodytes patagonica',
  146: 'albatros, mollymawk',
  147: 'baleine grise, baleine grise, poisson diabolo, Eschrichtius gibbosus,' +
      'Eschrichtius robustus',
  148: 'épaulard, tueur, orque, grampus, loup de mer, orcinus orca',
  149: 'dugong, dugong dugon',
  150: 'lion de mer',
  151: 'Chihuahua',
  152: 'épagneul japonais',
  153: 'chien maltais, terrier maltais, maltais',
  154: 'Pékinois, Pékinois, Peke',
  155: 'Shih-Tzu',
  156: 'Blenheim spaniel',
  157: 'papillon',
  158: 'jouet terrier',
  159: 'Rhodesian Ridgeback',
  160: 'Lévrier afghan, Afghan',
  161: 'basset, basset hound',
  162: 'Beagle',
  163: 'limier, limier',
  164: 'bluetick',
  165: 'coonhound noir et feu',
  166: 'Walker Hound, Walker Foxhound',
  167: 'Chien de renard anglais',
  168: 'redbone',
  169: 'barzoï, lévrier russe',
  170: 'lévrier irlandais',
  171: 'lévrier italien',
  172: 'whippet',
  173: 'Chien d\'Ibiza, Ibizan Podenco',
  174: 'elkhound norvégien, elkhound',
  175: 'loutre, loutre',
  176: 'Saluki, chien de gazelle',
  177: 'écossais cerf, cerf',
  178: 'Weimaraner',
  179: 'Staffordshire Bullterrier, Staffordshire Bull Terrier',
  180: 'American Staffordshire Terrier, Staffordshire Terrier, American Pit' +
      'bull terrier, pit bull terrier',
  181: 'Bedlington terrier',
  182: 'Border terrier',
  183: 'Kerry blue terrier',
  184: 'terrier irlandais',
  185: 'Norfolk terrier',
  186: 'Norwich terrier',
  187: 'Yorkshire terrier',
  188: 'fox terrier à poil dur',
  189: 'Lakeland terrier',
  190: 'Sealyham terrier, Sealyham',
  191: 'Airedale, Airedale terrier',
  192: 'cairn, cairn terrier',
  193: 'terrier australien',
  194: 'Dandie Dinmont, Dandie Dinmont terrier',
  195: 'Boston bull, Boston terrier',
  196: 'schnauzer miniature',
  197: 'schnauzer géant',
  198: 'schnauzer standard',
  199: 'Scotch terrier, Scottish Terrier, Scottie',
  200: 'terrier tibétain, chien de chrysanthème',
  201: 'terrier soyeux, Sydney soyeux',
  202: 'terrier de froment à enrobage doux',
  203: 'West Highland White Terrier',
  204: 'Lhasa, Lhasa apso',
  205: 'retriever à revêtement plat',
  206: 'retriever à poil bouclé',
  207: 'golden retriever',
  208: 'Labrador retriever',
  209: 'Retriever de la baie de Chesapeake',
  210: 'pointeur allemand à poil court',
  211: 'vizsla, pointeur hongrois',
  212: 'setter anglais',
  213: 'setter irlandais, poseur rouge',
  214: 'Gordon setter',
  215: 'Brittany spaniel',
  216: 'nombre, nombre d\'épagneul',
  217: 'springer anglais, springer anglais',
  218: 'Épagneul gallois',
  219: 'cocker spaniel, cocker anglais, cocker',
  220: 'Sussex spaniel',
  221: 'Irish water spaniel',
  222: 'kuvasz',
  223: 'schipperke',
  224: 'groenendael',
  225: 'malinois',
  226: 'briard',
  227: 'kelpie',
  228: 'komondor',
  229: 'Vieux chien de berger anglais, bobtail',
  230: 'Chien de berger Shetland, Chien de berger Shetland, Shetland',
  231: 'collie',
  232: 'Border Collie',
  233: 'Bouvier des Flandres, Bouviers des Flandres',
  234: 'Rottweiler',
  235: 'berger allemand, chien de berger allemand, chien de police allemand, alsacien',
  236: 'Doberman, Doberman pinscher',
  237: 'miniature pinscher',
  238: 'Grand chien de montagne suisse',
  239: 'chien de montagne bernois',
  240: 'Appenzeller',
  241: 'EntleBucher',
  242: 'boxer',
  243: 'bull mastiff',
  244: 'Mastiff tibétain',
  245: 'bouledogue français',
  246: 'Dogue Allemand',
  247: 'Saint Bernard, St Bernard',
  248: 'chien esquimau, husky',
  249: 'malamute, malemute, malamute d\'Alaska',
  250: 'husky sibérien',
  251: 'dalmatien, chien d’entraînement, chien de transport',
  252: 'affenpinscher, singe pinscher, chien singe',
  253: 'basenji',
  254: 'Carlin, Carlin-chien',
  255: 'Leonberg',
  256: 'Terre-Neuve, chien de Terre-Neuve',
  257: 'Grandes Pyrénées',
  258: 'Samoyed, Samoyede',
  259: 'poméranien',
  260: 'chow, chow chow',
  261: 'keeshond',
  262: 'Brabancon griffon',
  263: 'Pembroke, Pembroke Welsh corgi',
  264: 'Cardigan, Cardigan Welsh Corgi',
  265: 'caniche jouet',
  266: 'caniche miniature',
  267: 'caniche standard',
  268: 'Mexicain sans poil',
  269: 'loup des bois, loup gris, loup gris, Canis lupus',
  270: 'loup blanc, loup arctique, Canis lupus tundrarum',
  271: 'loup rouge, loup à crinière, Canis rufus, Canis niger',
  272: 'coyote, loup des prairies, loup en brosse, Canis latrans',
  273: 'dingo, warrigal, warragal, canis dingo',
  274: 'dhole, Cuon alpinus',
  275: 'Chien de chasse africain, chien hyène, chien de chasse du Cap, Lycaon pictus',
  276: 'hyène, hyène',
  277: 'renard roux, Vulpes vulpes',
  278: 'kit renard, Vulpes macrotis',
  279: 'Renard polaire, renard blanc, Alopex lagopus',
  280: 'renard gris, renard gris, Urocyon cinereoargenteus',
  281: 'chat tabby, chat tabby',
  282: 'chat tigre',
  283: 'chat persan',
  284: 'chat siamois, siamois',
  285: 'chat égyptien',
  286: 'cougar, puma, catamount, lion de montagne, peintre, panthère,' +
      'Felis concolor',
  287: 'lynx, catamount',
  288: 'léopard, Panthera pardus',
  289: 'léopard des neiges, once, Panthera uncia',
  290: 'jaguar, panthère, Panthera onca, Felis onca',
  291: 'lion, roi des bêtes, Panthera leo',
  292: 'tigre, Panthera tigris',
  293: 'guépard, chetah, Acinonyx jubatus',
  294: 'ours brun, bruin, Ursus arctos',
  295: 'Ours noir américain, ours noir, Ursus americanus, Euarctos' +
      'americanus',
  296: 'ours de glace, ours polaire, Ursus Maritimus, Thalarctos maritimus',
  297: 'ours paresseux, Melursus ursinus, Ursus ursinus',
  298: 'mangouste',
  299: 'suricate, mierkat',
  300: 'dendroctone du tigre',
  301: 'coccinelle, coccinelle, coccinelle, coccinelle, coccinelle',
  302: 'coléoptère terrestre, carabide',
  303: 'coléoptère à longues cornes, longicorne, longicorne',
  304: 'Coléoptère chrysomélidé',
  305: 'coléoptère de fumier',
  306: 'coléoptère du rhinocéros',
  307: 'charançon',
  308: 'voler',
  309: 'abeille',
  310: 'ant, emmet, pismire',
  311: 'sauterelle, trémie',
  312: 'cricket',
  313: 'canne, bâton de marche, insecte bâton',
  314: 'cafard, cafard',
  315: 'mante, mante',
  316: 'cigale, cicala',
  317: 'cicadelle',
  318: 'chrysope, mouche à chrysopes',
  319: 'libellule, aiguille à repriser, aiguille à repriser du diable, aiguille à coudre' +
      'mangeur de serpent, médecin de serpent, faucon moustique, faucon skeeter',
  320: 'demoiselle',
  321: 'amiral',
  322: 'ringlet, ringlet butterfly',
  323: 'monarque, papillon monarque, papillon d\'asclépiade, Danaus plexippus',
  324: 'papillon du chou',
  325: 'papillon soufre, papillon soufre',
  326: 'lycaenid, lycaenid butterfly',
  327: 'étoile de mer, étoile de mer',
  328: 'oursin',
  329: 'concombre de mer, holothurie',
  330: 'lapin des bois, lapin à queue blanche, lapin à queue blanche',
  331: 'lièvre',
  332: 'Angora, lapin Angora',
  333: 'hamster',
  334: 'porc-épic, hérisson',
  335: 'écureuil de renard, écureuil de renard oriental, Sciurus niger',
  336: 'marmotte',
  337: 'castor',
  338: 'cochon d\'Inde, Cavia cobaya',
  339: 'oseille',
  340: 'zèbre',
  341: 'porc, cochon, grunter, squealer, Sus scrofa',
  342: 'sanglier, sanglier, Sus scrofa',
  343: 'phacochère',
  344: 'hippopotame, hippopotame, cheval de rivière, Hippopotamus amphibius',
  345: 'boeuf',
  346: 'buffle d\'Amérique, buffle d\'Amérique, Bubalus bubalis',
  347: 'bison',
  348: 'ram, tup',
  349: 'bighorn, moutons bighorn, cimarron, rocheuses des montagnes bighorn, rocheuses' +
      'Mouton de montagne, Ovis canadensis',
  350: 'bouquetin, Capra ibex',
  351: 'hartebeest',
  352: 'impala, Aepyceros melampus',
  353: 'gazelle',
  354: 'Chameau d\'Arabie, dromadaire, Camelus dromedarius',
  355: 'lama',
  356: 'belette',
  357: 'vison',
  358: 'putec, fitch, foulmart, foumart, Mustela putorius',
  359: 'furet à pieds noirs, furet, Mustela nigripes',
  360: 'loutre',
  361: 'Moufette, putain, chatte en bois',
  362: 'blaireau',
  363: 'tatou',
  364: 'paresseux à trois doigts, ai, Bradypus tridactylus',
  365: 'orang-outan, orang, orang-outang, Pongo pygmaeus',
  366: 'gorille, gorille gorille',
  367: 'chimpanzé, chimpanzé, Pan troglodytes',
  368: 'gibbon, Hylobates lar',
  369: 'siamang, Hylobates syndactylus, Symphalangus syndactylus',
  370: 'guenon, guenon singe',
  371: 'patas, hussard, Erythrocebus patas',
  372: 'babouin',
  373: 'macaque',
  374: 'langur',
  375: 'colobus, colobus singe',
  376: 'singe proboscis, Nasalis larvatus',
  377: 'marmoset',
  378: 'capucins, rubans, Cebus capucinus',
  379: 'singe hurleur, hurleur',
  380: 'titi, titi singe',
  381: 'Singe-araignée, Ateles geoffroyi',
  382: 'singe écureuil, Saimiri sciureus',
  383: 'Chat de Madagascar, lémurien à queue annulée, Lemur catta',
  384: 'indri, indris, indri indri, indri brevicaudatus',
  385: 'éléphant indien, Elephas maximus',
  386: 'éléphant d\'Afrique, Loxodonta africana',
  387: 'petit panda, panda rouge, panda, ours, chat, ours, Ailurus fulgens',
  388: 'panda géant, panda, ours panda, ours coon, Ailuropoda melanoleuca',
  389: 'barracouta, snoek',
  390: 'anguille',
  391: 'coho, cohoe, coho, blue jack, saumon argenté, Oncorhynchus' +
      'kisutch',
  392: 'beauté du rock, Holocanthus tricolor',
  393: 'poisson anémone',
  394: 'esturgeon',
  395: 'gar, garfish, garpike, billfish, Lepisosteus, osseus',
  396: 'poisson-lion',
  397: 'puffer, pufferfish, blowfish, globefish',
  398: 'abaque',
  399: 'abaya',
  400: 'robe académique, robe académique, robe de juge',
  401: 'accordéon, accordéon de piano, boîte à presser',
  402: 'guitare acoustique',
  403: 'porte-avions, porte-avions, flattop, porte-avions d\'attaque',
  404: 'avion de ligne',
  405: 'dirigeable, dirigeable',
  406: 'autel',
  407: 'ambulance',
  408: 'amphibien, véhicule amphibie',
  409: 'horloge analogique',
  410: 'rucher, maison des abeilles',
  411: 'tablier',
  412: 'poubelle, poubelle, poubelle, poubelle, poubelle, poubelle,' +
      'poubelle, baril de poubelle, poubelle',
  413: 'fusil d\'assaut, fusil d\'assaut',
  414: 'sac à dos, sac à dos, sac à dos, sac à dos, sac à dos, sac à dos',
  415: 'boulangerie, pâtisserie, fournil',
  416: 'poutre d\'équilibre, poutre',
  417: 'ballon',
  418: 'stylo à bille, stylo à bille, stylo bille, stylo biro',
  419: 'Band Aid',
  420: 'banjo',
  421: 'bannister, balustrade, balustrade, balustres, main courante',
  422: 'barbell',
  423: 'chaise de coiffeur',
  424: 'salon de coiffure',
  425: 'grange',
  426: 'baromètre',
  427: 'tonneau, fût',
  428: 'brouette, chariot de jardin, chariot à gazon, brouette',
  429: 'baseball',
  430: 'basketball',
  431: 'bassinet',
  432: 'basson',
  433: 'bonnet de bain, bonnet de bain',
  434: 'serviette de bain',
  435: 'baignoire, baignoire, baignoire, baignoire',
  436: 'wagon de plage, break, wagon, break, wagon de plage, gare' +
      'waggon, waggon',
  437: 'phare, phare, phare, pharos',
  438: 'bécher',
  439: 'peaux d\'ours, busby, shako',
  440: 'bouteille de bière',
  441: 'verre à bière',
  442: 'bell cote, bell lit',
  443: 'bavette',
  444: 'vélo construit pour deux, vélo tandem, tandem',
  445: 'bikini, deux pièces',
  446: 'reliure à anneaux',
  447: 'jumelles, jumelles, lunettes d\'opéra',
  448: 'nichoir',
  449: 'hangar à bateaux',
  450: 'bobsleigh, bobsleigh, bob',
  451: 'cravate bolo, bolo, cravate bola, bola',
  452: 'bonnet, poke bonnet',
  453: 'bibliothèque',
  454: 'librairie, librairie, kiosque à journaux',
  455: 'bottlecap',
  456: 'arc',
  457: 'noeud papillon, noeud papillon',
  458: 'laiton, plaque commémorative, plaque',
  459: 'brassière, soutien-gorge, bandeau',
  460: 'brise-lames, aine, épi, taupe, pavois, digue, jetée',
  461: 'cuirasse, égide, egis',
  462: 'balai',
  463: 'seau, seau',
  464: 'boucle',
  465: 'gilet pare-balles',
  466: 'train à grande vitesse, balle',
  467: 'boucherie, marché de la viande',
  468: 'taxi, bidouille, taxi, taxi',
  469: 'chaudron, chaudron',
  470: 'bougie, cône, lumière de cire',
  471: 'canon',
  472: 'canoë',
  473: 'ouvre-boîtes, ouvre-boîtes',
  474: 'cardigan',
  475: 'miroir de voiture',
  476: 'carrousel, carrousel, manège, rond-point, tourbillon',
  477: 'kit de menuisier, kit d’outils',
  478: 'carton',
  479: 'roue de voiture',
  480: 'distributeur automatique de billets, distributeur automatique de billets, distributeur automatique de billets' +
      'guichet automatique, guichet automatique, guichet automatique, ATM',
  481: 'cassette',
  482: 'lecteur de cassettes',
  483: 'château',
  484: 'catamaran',
  485: 'lecteur CD',
  486: 'violoncelle, violoncelle',
  487: 'téléphone cellulaire, téléphone cellulaire, téléphone cellulaire, cellulaire, téléphone mobile',
  488: 'chaîne',
  489: 'clôture grillagée',
  490: 'cotte de mailles, courrier en anneau, courrier, armure en chaîne, armure en chaîne, armure en anneau' +
      'armure de ring',
  491: 'scie à chaîne, tronçonneuse',
  492: 'poitrine',
  493: 'chiffonnier, commode',
  494: 'carillon, cloche, gong',
  495: 'vaisselier, placard en porcelaine',
  496: 'bas de Noël',
  497: 'église, édifice d\'église',
  498: 'cinéma, salle de cinéma, salle de cinéma, cinéma, palais de l\'image',
  499: 'couperet, couperet à viande, hachoir',
  500: 'habitation de falaise',
  501: 'manteau',
  502: 'sabot, geta, patten, sabot',
  503: 'shaker',
  504: 'tasse de café',
  505: 'cafetière',
  506: 'bobine, spirale, volute, spire, hélice',
  507: 'serrure à combinaison',
  508: 'clavier d\'ordinateur, clavier',
  509: 'confiseries, confiseries, confiseries',
  510: 'porte-conteneurs, porte-conteneurs, porte-conteneurs',
  511: 'convertible',
  512: 'tire-bouchon, vis de bouteille',
  513: 'cornet, corne, trompette, atout',
  514: 'botte de cow-boy',
  515: 'chapeau de cow-boy, chapeau de dix gallons',
  516: 'berceau',
  517: 'grue',
  518: 'casque de protection',
  519: 'caisse',
  520: 'berceau, lit bébé',
  521: 'Crock Pot',
  522: 'balle de croquet',
  523: 'béquille',
  524: 'cuirasse',
  525: 'digue, digue',
  526: 'bureau',
  527: 'ordinateur de bureau',
  528: 'composer le téléphone, composer le téléphone',
  529: 'couche, couche, serviette de table',
  530: 'horloge numérique',
  531: 'montre numérique',
  532: 'table à manger, plateau',
  533: 'Dishrag, torchon',
  534: 'lave-vaisselle, lave-vaisselle, lave-vaisselle',
  535: 'frein à disque, frein à disque',
  536: 'quai, amarrage, amarrage',
  537: 'traîneau à chien, traîneau à chien, traîneau à chien',
  538: 'dôme',
  539: 'paillasson, tapis de bienvenue',
  540: 'plate-forme de forage, plate-forme offshore',
  541: 'tambour, membranophone, tympan',
  542: 'pilon',
  543: 'haltère',
  544: 'four hollandais',
  545: 'ventilateur électrique, ventilateur',
  546: 'guitare électrique',
  547: 'locomotive électrique',
  548: 'centre de divertissement',
  549: 'enveloppe',
  550: 'machine à expresso',
  551: 'poudre pour le visage',
  552: 'boa de plumes, boa',
  553: 'dossier, classeur, classeur',
  554: 'bateau pompier',
  555: 'camion de pompiers',
  556: 'pare-feu, pare-feu',
  557: 'mât de drapeau, hampe de drapeau',
  558: 'flûte traversière transversale',
  559: 'chaise pliante',
  560: 'casque de football',
  561: 'chariot élévateur',
  562: 'fontaine',
  563: 'stylo-plume',
  564: 'à baldaquin',
  565: 'wagon de fret',
  566: 'Cor français, corne',
  567: 'poêle, poêle à frire, poêle',
  568: 'manteau de fourrure',
  569: 'camion à ordures, chariot à poussière',
  570: 'masque à gaz, respirateur, casque à gaz',
  571: 'pompe à essence, pompe à essence, pompe à essence, distributeur d\'îlots',
  572: 'gobelet',
  573: 'kart',
  574: 'balle de golf',
  575: 'voiturette de golf, voiturette de golf',
  576: 'gondole',
  577: 'gong, tam-tam',
  578: 'robe',
  579: 'piano à queue, grand',
  580: 'serre, pépinière, serre',
  581: 'calandre, calandre',
  582: 'épicerie, épicerie, marché alimentaire, marché',
  583: 'guillotine',
  584: 'barrette',
  585: 'fixatif',
  586: 'half track',
  587: 'marteau',
  588: 'panier',
  589: 'souffleuse à main, sèche-cheveux, sèche-cheveux, sèche-cheveux, sèche-cheveux',
  590: 'ordinateur de poche, micro-ordinateur de poche',
  591: 'mouchoir, hankie, mouchoir, clé en main',
  592: 'disque dur, disque dur, disque fixe',
  593: 'harmonica, orgue à bouche, harpe, harpe à bouche',
  594: 'harpe',
  595: 'moissonneuse, moissonneuse',
  596: 'hachette',
  597: 'étui',
  598: 'home cinema, home cinema',
  599: 'nid d\'abeille',
  600: 'crochet, griffe',
  601: 'jupe-tête, crinoline',
  602: 'barre horizontale, barre haute',
  603: 'charrette à cheval, charrette à cheval',
  604: 'sablier',
  605: 'iPod',
  606: 'fer, fer à lisser',
  607: 'jack-o \' - lantern ',
  608: 'jean, blue jean, denim',
  609: 'jeep, landrover',
  610: 'maillot, t-shirt, tee-shirt',
  611: 'puzzle',
  612: 'jinrikisha, ricksha, pousse-pousse',
  613: 'joystick',
  614: 'kimono',
  615: 'genouillère',
  616: 'noeud',
  617: 'blouse de laboratoire, blouse de laboratoire',
  618: 'louche',
  619: 'abat-jour, abat-jour',
  620: 'ordinateur portable, ordinateur portable',
  621: 'tondeuse à gazon, tondeuse',
  622: 'bouchon d\'objectif, cache-objectif',
  623: 'coupe-papier, coupe-papier, couteau à papier',
  624: 'bibliothèque',
  625: 'canot de sauvetage',
  626: 'briquet, lumière, allumeur, allumeur',
  627: 'limousine, limo',
  628: 'paquebot, paquebot',
  629: 'lipstick, lip rouge',
  630: 'mocassin',
  631: 'lotion',
  632: 'haut-parleur, haut-parleur, haut-parleur, système de haut-parleur, haut-parleur' ​​+
      'système',
  633: 'loupe, loupe de bijoutier',
  634: 'lumbermill, scierie',
  635: 'compas magnétique',
  636: 'mailbag, postbag',
  637: 'boîte aux lettres, boîte aux lettres',
  638: 'maillot',
  639: 'maillot, combinaison de tank',
  640: 'plaque d\'égout',
  641: 'maraca',
  642: 'marimba, xylophone',
  643: 'masque',
  644: 'allumette',
  645: 'maypole',
  646: 'labyrinthe, labyrinthe',
  647: 'tasse à mesurer',
  648: 'armoire à pharmacie, armoire à pharmacie',
  649: 'mégalithe, structure mégalithique',
  650: 'microphone, mike',
  651: 'micro-ondes, four à micro-ondes',
  652: 'uniforme militaire',
  653: 'boîte de lait',
  654: 'minibus',
  655: 'mini-jupe, mini',
  656: 'monospace',
  657: 'missile',
  658: 'mitaine',
  659: 'bol à mélanger',
  660: 'maison mobile, maison préfabriquée',
  661: 'Modèle T',
  662: 'modem',
  663: 'monastère',
  664: 'moniteur',
  665: 'cyclomoteur',
  666: 'mortier',
  667: 'mortier',
  668: 'mosquée',
  669: 'moustiquaire',
  670: 'scooter, scooter',
  671: 'VTT, vélo tout terrain, tout-terrain',
  672: 'tente de montagne',
  673: 'souris, souris d\'ordinateur',
  674: 'piège à souris',
  675: 'camion de déménagement',
  676: 'museau',
  677: 'clou',
  678: 'Minerve',
  679: 'collier',
  680: 'mamelon',
  681: 'ordinateur portable, ordinateur portable',
  682: 'obélisque',
  683: 'hautbois, hautbois, hautbois',
  684: 'ocarina, patate douce',
  685: 'compteur kilométrique, compteur kilométrique, compteur kilométrique, compteur kilométrique',
  686: 'filtre à huile',
  687: 'orgue, orgue à tuyaux',
  688: 'oscilloscope, oscilloscope, oscilloscope à rayons cathodiques, CRO',
  689: 'jupe longue',
  690: 'char à boeufs',
  691: 'masque à oxygène',
  692: 'paquet',
  693: 'pagaie, pagaie de bateau',
  694: 'roue à aubes, roue à aubes',
  695: 'cadenas',
  696: 'pinceau',
  697: 'pyjama, pyjama, pj \'s, jammies',
  698: 'palais',
  699: 'pipe à pan, pipe pandean, syrinx',
  700: 'essuie-tout',
  701: 'parachute, chute',
  702: 'barres parallèles, barres',
  703: 'banc de parc',
  704: 'parcomètre',
  705: 'voiture particulière, autocar, calèche',
  706: 'patio, terrasse',
  707: 'téléphone payant, poste payant',
  708: 'socle, socle, repose-pieds',
  709: 'boîte à crayons, étui à crayons',
  710: 'taille-crayon',
  711: 'parfum, essence',
  712: 'boîte de Pétri',
  713: 'photocopieur',
  714: 'pick, plectre, plectron',
  715: 'pickelhaube',
  716: 'palissade, paling',
  717: 'ramassage, camionnette',
  718: 'jetée',
  719: 'tirelire, penny bank',
  720: 'bouteille de pilules',
  721: 'oreiller',
  722: 'balle de ping-pong',
  723: 'moulinet',
  724: 'pirate, bateau pirate',
  725: 'pichet, aiguière',
  726: 'avion de menuisier, avion de menuisier',
  727: 'planétarium',
  728: 'sachet en plastique',
  729: 'porte-assiettes',
  730: 'charrue, charrue',
  731: 'plongeur, aide du plombier',
  732: 'Appareil photo Polaroid, appareil photo Polaroid Land',
  733: 'pôle',
  734: 'fourgon de police, fourgon de police, chariot de paddy, chariot de patrouille, chariot, noir' +
      'Maria',
  735: 'poncho',
  736: 'table de billard, table de billard, table de billard',
  737: 'bouteille de boisson gazeuse, bouteille de soda',
  738: 'pot, pot de fleurs',
  739: 'tour de potier',
  740: 'perceuse',
  741: 'tapis de prière, tapis de prière',
  742: 'imprimante',
  743: 'prison, maison d\'arrêt',
  744: 'projectile, missile',
  745: 'projecteur',
  746: 'rondelle, rondelle de hockey',
  747: 'sac de boxe, sac de frappe, balle de boxe, balle de poing',
  748: 'bourse',
  749: 'plume, plume',
  750: 'couette, édredon, confort, feuilletée',
  751: 'coureur, voiture de course, voiture de course',
  752: 'raquette, raquette',
  753: 'radiateur',
  754: 'radio, sans fil',
  755: 'radiotélescope, réflecteur radio',
  756: 'baril de pluie',
  757: 'véhicule de loisirs, VR, RV',
  758: 'moulinet',
  759: 'appareil photo reflex',
  760: 'réfrigérateur, glacière',
  761: 'télécommande, télécommande',
  762: 'restaurant, restaurant, salle à manger, restaurant',
  763: 'revolver, six coups, six coups',
  764: 'fusil',
  765: 'rocking chair, rocker',
  766: 'rôtisserie',
  767: 'gomme à effacer, gomme, gomme à crayon',
  768: 'ballon de rugby',
  769: 'règle, règle',
  770: 'chaussure de course',
  771: 'sûr',
  772: 'goupille de sécurité',
  773: 'Salière, salière',
  774: 'sandale',
  775: 'sarong',
  776: 'saxophone, saxophone',
  777: 'fourreau',
  778: 'balance, appareil de pesage',
  779: 'autobus scolaire',
  780: 'goélette',
  781: 'tableau de bord',
  782: 'écran, écran cathodique',
  783: 'vis',
  784: 'tournevis',
  785: 'ceinture de sécurité, ceinture de sécurité',
  786: 'machine à coudre',
  787: 'bouclier, bouclier',
  788: 'magasin de chaussures, magasin de chaussures, magasin de chaussures',
  789: 'shoji',
  790: 'panier',
  791: 'panier',
  792: 'pelle',
  793: 'bonnet de douche',
  794: 'rideau de douche',
  795: 'ski',
  796: 'masque de ski',
  797: 'sac de couchage',
  798: 'règle coulissante',
  799: 'porte coulissante',
  800: 'fente, bandit à un bras',
  801: 'tuba',
  802: 'motoneige',
  803: 'chasse-neige, chasse-neige',
  804: 'distributeur de savon',
  805: 'ballon de foot',
  806: 'chaussette',
  807: 'antenne solaire, capteur solaire, four solaire',
  808: 'sombrero',
  809: 'bol à soupe',
  810: 'barre d\'espace',
  811: 'appareil de chauffage',
  812: 'navette spatiale',
  813: 'spatule',
  814: 'bateau à moteur',
  815: 'toile d\'araignée, toile d\'araignée',
  816: 'broche',
  817: 'voiture de sport, voiture de sport',
  818: 'spotlight, spot',
  819: 'stage',
  820: 'locomotive à vapeur',
  821: 'pont en arc en acier',
  822: 'tambour d\'acier',
  823: 'stéthoscope',
  824: 'étole',
  825: 'mur de pierre',
  826: 'chronomètre, chronomètre',
  827: 'cuisinière',
  828: 'passoire',
  829: 'tramway, tram, tramway, tramway, tramway',
  830: 'civière',
  831: 'canapé studio, lit de repos',
  832: 'stupa, tope',
  833: 'sous-marin, péniche, sous-marin, sous-marin',
  834: 'costume, costume de vêtements',
  835: 'cadran solaire',
  836: 'sunglass',
  837: 'lunettes de soleil, lunettes noires, lunettes de soleil',
  838: 'crème solaire, écran solaire, écran solaire',
  839: 'pont suspendu',
  840: 'écouvillon, vadrouille, vadrouille',
  841: 'sweat-shirt',
  842: 'caleçons de bain, caleçons de bain',
  843: 'swing',
  844: 'interrupteur, interrupteur électrique, interrupteur électrique',
  845: 'seringue',
  846: 'lampe de table',
  847: 'char, char de l\'armée, véhicule de combat blindé, véhicule de combat blindé',
  848: 'lecteur de bande',
  849: 'théière',
  850: 'nounours, ours en peluche',
  851: 'télévision, système de télévision',
  852: 'balle de tennis',
  853: 'chaume, toit de chaume',
  854: 'rideau de théâtre, rideau de théâtre',
  855: 'dé à coudre',
  856: 'batteuse, batteuse, batteuse',
  857: 'trône',
  858: 'toit en tuiles',
  859: 'grille-pain',
  860: 'tabac, tabac, tabac',
  861: 'siège de toilette',
  862: 'torche',
  863: 'totem',
  864: 'dépanneuse, voiture de remorquage, dépanneuse',
  865: 'magasin de jouets',
  866: 'tracteur',
  867: 'camion remorque, semi-remorque, camion, camion, camion, articulé' +
      'camion, semi',
  868: 'plateau',
  869: 'trench coat',
  870: 'tricycle, trike, vélocipède',
  871: 'trimaran',
  872: 'trépied',
  873: 'arc de triomphe',
  874: 'trolleybus, tramway, chariot sans rail',
  875: 'trombone',
  876: 'cuve, cuve',
  877: 'tourniquet',
  878: 'clavier de machine à écrire',
  879: 'parapluie',
  880: 'monocycle, monocycle',
  881: 'piano droit, droit',
  882: 'aspirateur, aspirateur',
  883: 'vase',
  884: 'voûte',
  885: 'velours',
  886: 'distributeur automatique',
  887: 'vêtement',
  888: 'viaduc',
  889: 'violon, violon',
  890: 'volleyball',
  891: 'gaufrier',
  892: 'horloge murale',
  893: 'portefeuille, porte-billets, bloc-notes, porte-monnaie',
  894: 'armoire, penderie, presse',
  895: 'avion de guerre, avion militaire',
  896: 'lavabo, lavabo, lavabo, lavabo, lavabo',
  897: 'laveuse, laveuse automatique, machine à laver',
  898: 'bouteille d\'eau',
  899: 'cruche d\'eau',
  900: 'château d\'eau',
  901: 'pichet de whisky',
  902: 'sifflet',
  903: 'perruque',
  904: 'écran de fenêtre',
  905: 'store de fenêtre',
  906: 'cravate de Windsor',
  907: 'bouteille de vin',
  908: 'aile',
  909: 'wok',
  910: 'cuillère en bois',
  911: 'laine, laine, laine',
  912: 'clôture de ver, clôture de serpent, clôture de rail en serpent, clôture de Virginie',
  913: 'épave',
  914: 'yawl',
  915: 'yourte',
  916: 'site Web, site Web, site Web, site',
  917: 'bande dessinée',
  918: 'mots croisés, mots croisés',
  919: 'panneau de rue',
  920: 'feu de circulation, feu de signalisation, feu stop',
  921: 'jaquette, jaquette, jaquette',
  922: 'menu',
  923: 'plaque',
  924: 'guacamole',
  925: 'consommation',
  926: 'hot pot, hotpot',
  927: 'bagatelle',
  928: 'crème glacée, crème glacée',
  929: 'sucette glacée, sucette, sucette, sucette glacée',
  930: 'pain français',
  931: 'bagel, beigel',
  932: 'bretzel',
  933: 'cheeseburger',
  934: 'hot dog, hot dog, red hot',
  935: 'purée de pomme de terre',
  936: 'chou pommé',
  937: 'brocolis',
  938: 'chou-fleur',
  939: 'courgettes, courgettes',
  940: 'courge spaghetti',
  941: 'courge poivrée',
  942: 'courge musquée',
  943: 'concombre, gobelet',
  944: 'artichaut, globe d\'artichaut',
  945: 'poivron',
  946: 'cardon',
  947: 'champignon',
  948: 'Granny Smith',
  949: 'fraise',
  950: 'orange',
  951: 'citron',
  952: 'figue',
  953: 'ananas, ananas',
  954: 'banane',
  955: 'fruit du jacquier, jak, jack',
  956: 'pomme pâtissière',
  957: 'grenade',
  958: 'foin',
  959: 'carbonara',
  960: 'sauce au chocolat, sirop de chocolat',
  961: 'pâte',
  962: 'pain de viande, pain de viande',
  963: 'pizza, pizza',
  964: 'potpie',
  965: 'burrito',
  966: 'vin rouge',
  967: 'expresso',
  968: 'tasse',
  969: 'lait de poule',
  970: 'alp',
  971: 'bulle',
  972: 'falaise, goutte à goutte',
  973: 'récif corallien',
  974: 'geyser',
  975: 'au bord du lac, au bord du lac',
  976: 'promontoire, pointe, tête, avant-pays',
  977: 'barre de sable, barre de sable',
  978: 'bord de mer, côte, côte, côte de la mer',
  979: 'vallée, vallée',
  980: 'volcan',
  981: 'joueur de baseball, joueur de baseball',
  982: 'marié, époux',
  983: 'scuba diver',
  984: 'colza',
  985: 'marguerite',
  986: 'pantoufle de dame jaune, pantoufle de dame jaune, Cypripedium calceolus,' +
      'Cypripedium parviflorum',
  987: 'maïs',
  988: 'gland',
  989: 'hanche, églantier, églantier',
  990: 'buckeye, marronnier d\'Inde, conker',
  991: 'champignon corail',
  992: 'agaric',
  993: 'gyromitra',
  994: 'stinkhorn, charion mycète',
  995: 'étoile de terre',
  996: 'poule-des-bois, poule des bois, Polyporus frondosus, Grifola' +
      'frondosa',
  997: 'bolete',
  998: 'oreille, épi, capitule',
  999: 'Papier hygiénique, papier hygiénique, papier hygiénique'
};